/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.chat.client;

/**
 *
 * @author rocco
 */
public class ChatFrame extends javax.swing.JFrame {
    MessageReader messageReader;
    MessageSender messageSender;

    /**
     * Creates new form ChatFrame
     */
    public ChatFrame() {
        initComponents();
              
        setTitle("Chat-Client");
        setSize(900, 600);
        setLocationRelativeTo(null);
        setVisible(true);
    }
    
    public void setMessageReader(MessageReader messageReader) {
        this.messageReader = messageReader;
    }
    
    public void setMessageSender(MessageSender messageSender) {
        this.messageSender = messageSender;
    }
    
    public void appendMessage(String message) {
        chat_area.append(message + "\n");
    }
    
    // aggiunge alla textArea il server a cui è collegato il client
    public void addServer(String str) {
        server_list_area.append("\n" + str + "\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        disconnect_button = new javax.swing.JButton();
        chat_field = new javax.swing.JTextField();
        send_chat_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        chat_area = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        server_list_area = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        disconnect_button.setText("Disconnetti");
        disconnect_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnect_buttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        getContentPane().add(disconnect_button, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 135;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        getContentPane().add(chat_field, gridBagConstraints);

        send_chat_button.setText(">");
        send_chat_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_chat_buttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        getContentPane().add(send_chat_button, gridBagConstraints);

        chat_area.setEditable(false);
        chat_area.setColumns(20);
        chat_area.setRows(5);
        jScrollPane1.setViewportView(chat_area);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 261;
        gridBagConstraints.ipady = 246;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        server_list_area.setEditable(false);
        server_list_area.setColumns(20);
        server_list_area.setRows(5);
        server_list_area.setText("Server");
        jScrollPane2.setViewportView(server_list_area);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 246;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   // invio dei messaggi al server
    private void send_chat_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_chat_buttonActionPerformed
        // TODO add your handling code here:
        if(!chat_field.getText().isEmpty()) {
            // invia messaggio al server
            messageSender.sendMessage(chat_field.getText());
            chat_area.append("Tu: " + chat_field.getText() + "\n");
            chat_field.setText("");
        }
    }//GEN-LAST:event_send_chat_buttonActionPerformed

    // chiama il metodo per disconnettersi dal server
    private void disconnect_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnect_buttonActionPerformed
        // TODO add your handling code here:
        // rilascia le risorse relative ai thread
        // messageReader.closeResources();
        // termina la connessione
        Client.disconnectFromServer();
        messageSender.closeResources();
        

    }//GEN-LAST:event_disconnect_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea chat_area;
    private javax.swing.JTextField chat_field;
    private javax.swing.JButton disconnect_button;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton send_chat_button;
    private javax.swing.JTextArea server_list_area;
    // End of variables declaration//GEN-END:variables
}
