/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.chat.client;

/**
 *
 * @author rocco
 */
public class ChatFrame extends javax.swing.JFrame {
    MessageReader messageReader;
    MessageSender messageSender;

    /**
     * Creates new form ChatFrame
     */
    public ChatFrame() {
        initComponents();
              
        setTitle("Chat-Client");
        setSize(900, 600);
        setLocationRelativeTo(null);
        setVisible(true);
        
        users_list_area.append("Utenti in chat: \n");
    }
    
    public void setMessageReader(MessageReader messageReader) {
        this.messageReader = messageReader;
    }
    
    public void setMessageSender(MessageSender messageSender) {
        this.messageSender = messageSender;
    }
    
    public void appendMessage(String message) {
        chat_area.append(message + "\n");
    }
    
    // aggiunge alla textArea il server a cui è collegato il client
    public void addServer(String str) {
        server_label.setText(str);
    }
    
    public void updateClientList(String client_list) {
        users_list_area.setText(client_list);
    }
    
    private void sendMessageToServer() {
        if (!chat_field.getText().isEmpty()) {
            // invia messaggio al server
            messageSender.sendMessage(chat_field.getText());
            chat_area.append("Tu: " + chat_field.getText() + "\n");
            chat_field.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        disconnect_button = new javax.swing.JButton();
        chat_field = new javax.swing.JTextField();
        send_chat_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        chat_area = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        users_list_area = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        server_label = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        disconnect_button.setText("Disconnetti");
        disconnect_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnect_buttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 7, 5, 7);
        getContentPane().add(disconnect_button, gridBagConstraints);

        chat_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chat_fieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 135;
        gridBagConstraints.insets = new java.awt.Insets(6, 5, 4, 5);
        getContentPane().add(chat_field, gridBagConstraints);

        send_chat_button.setText(">");
        send_chat_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_chat_buttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(send_chat_button, gridBagConstraints);

        jScrollPane1.setBorder(new javax.swing.border.MatteBorder(null));

        chat_area.setEditable(false);
        chat_area.setColumns(20);
        chat_area.setRows(5);
        jScrollPane1.setViewportView(chat_area);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jScrollPane2.setBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        users_list_area.setEditable(false);
        users_list_area.setColumns(20);
        users_list_area.setRows(5);
        users_list_area.setPreferredSize(new java.awt.Dimension(276, 110));
        jScrollPane2.setViewportView(users_list_area);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jScrollPane2, gridBagConstraints);

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        jPanel1.add(server_label, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(jPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(filler1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   // invio dei messaggi al server
    private void send_chat_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_chat_buttonActionPerformed
        // TODO add your handling code here:
        sendMessageToServer();
    }//GEN-LAST:event_send_chat_buttonActionPerformed

    // chiama il metodo per disconnettersi dal server
    private void disconnect_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnect_buttonActionPerformed
        // TODO add your handling code here:
        // termina la connessione
        Client.disconnectFromServer();
        
        // rilascia le risorse
        messageSender.interrupt();
    }//GEN-LAST:event_disconnect_buttonActionPerformed

    // invio dei messaggi al server
    private void chat_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chat_fieldActionPerformed
        // TODO add your handling code here:
        sendMessageToServer();
    }//GEN-LAST:event_chat_fieldActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea chat_area;
    private javax.swing.JTextField chat_field;
    private javax.swing.JButton disconnect_button;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton send_chat_button;
    private javax.swing.JLabel server_label;
    private javax.swing.JTextArea users_list_area;
    // End of variables declaration//GEN-END:variables
}
